name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Verify Maven Wrapper Exists
      run: |
        if [ ! -f ./mvnw ]; then
          echo "Error: Maven wrapper file (mvnw) not found!"
          exit 1
        fi

    - name: Ensure Maven Wrapper Has Correct Permissions
      run: |
        ls -l ./mvnw
        chmod +x ./mvnw
        ls -l ./mvnw

    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: "--file=./pom.xml -d"